### ISSUE TITLE
More Info and WhiteList doesn't appear.

### ISSUE THREAD

**Issue by dbershev** [WaLLy3K/Pi-hole-Block-Page#1]
Hi there,

I'm trying to get the new block page to play nice without having a landing page defined using ubuntu 14.04. This is what I get when I browse to a blocked site. http://imgur.com/a/LBZms

My .ini file can be found here. http://pastebin.com/tB9fDweM

Thanks!

**Comment by WaLLy3K** [comment]
Sorry to hear you're having issues, but I'm totally happy to help out! The expected behaviour for that message is that you've arrived at this domain, but it doesn't appear in any block lists (e.g: a secondary local domain name). Unfortunately, just placing in your config fails to reproduce the issue on my end.

Could I get you to run the following command in SSH and return the output here? `wget -qO - "http://pi.hole/admin/scripts/pi-hole/php/queryads.php?domain=doubleclick.net&exact" | egrep "(blacklist\.|\.domains).*\([1-9]"`

It *should* return several matching lines (in which case I'm parsing something incorrectly) or it will return no results at all (in which case there may be an issue with Pi-hole itself). In either case, it will give me a better idea how to proceed.

Thanks!

**Comment by dbershev** [comment]
Yeah, it returned several lines from the various blocklists.

user@pidns01:~$ wget -qO - "http://pi.hole/admin/scripts/pi-hole/php/queryads.php?domain=doubleclick.net&exact" | egrep "(blacklist\.|\.domains).*\([1-9]"
data: ::: /etc/pihole/list.0.raw.githubusercontent.com.domains (1 results)
data: ::: /etc/pihole/list.2.sysctl.org.domains (1 results)
data: ::: /etc/pihole/list.5.s3.amazonaws.com.domains (1 results)
data: ::: /etc/pihole/list.6.hosts-file.net.domains (1 results)

I've also noticed that if I uncomment the landing page or the domain, it comes up with a different error saying no domain defined in phbb config.

**Comment by WaLLy3K** [comment]
> I've also noticed that if I uncomment the landing page or the domain, it comes up with a different error saying no domain defined in phbb config.

Interesting! That means there's definitely something I'm parsing incorrectly, but I'm not sure what yet. Could I get you to perform the following? (I don't have any built in debugging tools yet, sorry!)

```
html=$(grep server.document-root /etc/lighttpd/lighttpd.conf | awk -F\" '{print $2}')
mv $html/index.php $html/index.php.BAK
sudo wget -q https://raw.githubusercontent.com/WaLLy3K/wally3k.github.io/master/debug.php -O "$html/index.php"
```

Then browse to [http://doubleclick.net?debug](http://doubleclick.net?debug) and provide the output.

Thanks! :smile:

**Comment by dbershev** [comment]
Sure thing. glad to help out :)

Initial output:
Array
(
    [0] => data: ::: /etc/pihole/list.0.raw.githubusercontent.com.domains (1 results)

    [9] => data: ::: /etc/pihole/list.2.sysctl.org.domains (1 results)

    [22] => data: ::: /etc/pihole/list.5.s3.amazonaws.com.domains (1 results)

    [27] => data: ::: /etc/pihole/list.6.hosts-file.net.domains (1 results)

)

Cleaned output:
Array
(
    [0] => 0
    [9] => 2
    [22] => 5
    [27] => 6
)

Featured Total: 0

**Comment by WaLLy3K** [comment]
I suspect I know what's happening now, so give both http://doubleclick.net a try for the quick fix I implemented, as well as providing the output for http://doubleclick.net?debug after updating to this version:

```
html=$(grep server.document-root /etc/lighttpd/lighttpd.conf | awk -F\" '{print $2}')
sudo wget -q https://raw.githubusercontent.com/WaLLy3K/wally3k.github.io/master/debug.php -O "$html/index.php"
```

Thanks for your ongoing patience!

**Comment by dbershev** [comment]
Yes sir, we're getting closer!
http://imgur.com/a/0xBVv

`Warning: in_array() expects at least 2 parameters, 1 given in /var/www/html/index.php on line 41

Warning: file(adlists.default): failed to open stream: No such file or directory in /var/www/html/index.php on line 153

Warning: preg_grep() expects parameter 2 to be array, boolean given in /var/www/html/index.php on line 153

Warning: array_values() expects parameter 1 to be array, null given in /var/www/html/index.php on line 153

[$urlListCount] Total number of installed blocklists: 0
[$listMatches] Ad Query returned 4 results
[$listMatches] Sorted Ad Query Numbers: 0, 2, 5, 6
Featured total list was larger than urlListCount
[$featuredTotal] Featured Total: 4


Notice:  Uninitialized string offset: 0 in /var/www/html/index.php on line 201



Notice:  Uninitialized string offset: 0 in /var/www/html/index.php on line 202



Notice:  Uninitialized string offset: 0 in /var/www/html/index.php on line 203



Notice:  Uninitialized string offset: 0 in /var/www/html/index.php on line 204



Notice:  Uninitialized string offset: 2 in /var/www/html/index.php on line 201



Notice:  Uninitialized string offset: 2 in /var/www/html/index.php on line 202



Notice:  Uninitialized string offset: 2 in /var/www/html/index.php on line 203



Notice:  Uninitialized string offset: 2 in /var/www/html/index.php on line 204



Notice:  Uninitialized string offset: 5 in /var/www/html/index.php on line 201



Notice:  Uninitialized string offset: 5 in /var/www/html/index.php on line 202



Notice:  Uninitialized string offset: 5 in /var/www/html/index.php on line 203



Notice:  Uninitialized string offset: 5 in /var/www/html/index.php on line 204



Notice:  Uninitialized string offset: 6 in /var/www/html/index.php on line 201



Notice:  Uninitialized string offset: 6 in /var/www/html/index.php on line 202



Notice:  Uninitialized string offset: 6 in /var/www/html/index.php on line 203



Notice:  Uninitialized string offset: 6 in /var/www/html/index.php on line 204

Debug output complete`

**Comment by WaLLy3K** [comment]
> Warning: file(adlists.default): failed to open stream: No such file or directory in /var/www/html/index.php on line 153
> [$urlListCount] Total number of installed blocklists: 0

Out of all the things I was expecting, it certainly wasn't that. Let's see if [better adlists checking](https://github.com/WaLLy3K/wally3k.github.io/commit/f585a2656dd81db5f7413c99b7ee256a3f036b83) corrects that:

```
html=$(grep server.document-root /etc/lighttpd/lighttpd.conf | awk -F\" '{print $2}')
sudo wget -q https://raw.githubusercontent.com/WaLLy3K/wally3k.github.io/master/debug.php -O "$html/index.php"
```

**Comment by dbershev** [comment]
We have success!

[$urlListCount] Total number of installed blocklists: 7
[$listMatches] Ad Query returned 4 results
[$listMatches] Sorted Ad Query Numbers: 0, 2, 5, 6
[$featuredTotal] Featured Total: 4
Debug output complete

**Comment by WaLLy3K** [comment]
Much better! Does the block page work as expected without `?debug` now?

**Comment by dbershev** [comment]
Yes it does! Thanks for your help! I look forward to future updates and features

**Comment by WaLLy3K** [comment]
Issue resolved in [latest update](https://github.com/WaLLy3K/Pi-hole-Block-Page/commit/e10ff17489b45f25fb67044a8cc9a11a225f9c30), thank you very much for the report!

To apply this fix, please run the following:

```
html=$(grep server.document-root /etc/lighttpd/lighttpd.conf | awk -F\" '{print $2}')
sudo wget -q https://raw.githubusercontent.com/WaLLy3K/Pi-hole-Block-Page/master/index.php -O "$html/index.php"
```

/cc @canihavesomecoffee
