### ISSUE TITLE
Adguard English Filter

### ISSUE THREAD

**Issue by xxcriticxx** [WaLLy3K/Pi-hole-Block-Page#14]
@WaLLy3K can you please create pihole list for Adguard English Filter list. 

link:

`https://adguard.com/en/filter-rules.html?id=2`

**Comment by WaLLy3K** [comment]
I'll investigate this within the day and see if it adds anything that other lists don't already have. :)

**Comment by xxcriticxx** [comment]
its easylist modified by adguard team

**Comment by WaLLy3K** [comment]
From what I can tell: It appears that the *usuable* portion of the Adguard English list is just a section of the content available on the [Adguard DNS](https://filters.adtidy.org/extension/chromium/filters/15.txt) list, which has a [Pi-hole compatible mirror here](http://v.firebog.net/hosts/AdguardDNS.txt).

If there's something I've overlooked, definitely make sure to let me know!

**Comment by xxcriticxx** [comment]
got it that was simple thank you

**Comment by WaLLy3K** [comment]
No worries :) You're totally welcome to let me know of other lists you'd like mirrored, if/when you find any.
