### ISSUE TITLE
More Info/Whitelisting

### ISSUE THREAD

**Issue by Cliq3000** [WaLLy3K/Pi-hole-Block-Page#15]
Hello,

I'm unable to get "more info" and the manual whitelisting option for users if they have the password. I've commented out moreText, lessText, whiteInput and whiteText but still just seeing the "Back to Safety" option. I apologize if I may be missing something.

**Comment by WaLLy3K** [comment]
To confirm that I'm understanding the issue: If a page has been manually blacklisted, you don't get a "More Info" button. Is that correct?

If so: this is currently the expected behaviour, but I'm happy to look into having the option to allow whitelisting a manually blacklisted page!

**Comment by Cliq3000** [comment]
Is there a way to have it set like the picture you have? http://i.imgur.com/KIn6Yxp.png

**Comment by Cliq3000** [comment]
Ahhh. I assumed that the more info and the option to whitelist was for manually blacklisted domains as well as auto blacklisted domains. I think the having the same screen for the manually blacklisted domains would be great. Thanks for the quick response!

**Comment by WaLLy3K** [comment]
I've been spending a lot of my time directly on the Pi-hole project, and haven't had time for this. I'll be looking to officially integrate the block page, so I'll close this ticket and keep it in mind for an official release :)
