### ISSUE TITLE
Whitelist button disabled, I have an admin password?

### ISSUE THREAD

**Issue by DarthKeizer** [WaLLy3K/Pi-hole-Block-Page#16]
Hey man, can you help a brother out :)? Also can you make a nice skin for the page

**Comment by WaLLy3K** [comment]
Sorry to hear you're having issues! Could you provide the output of `http://doubleclick.net?debug=conf`? That should hopefully help me understand why the button is disabled.

Also, what's wrong with the current skin? :)

**Comment by WaLLy3K** [comment]
Resolved the issue on Twitter, closing issue.
