### ISSUE TITLE
Getting block page to run on docker installation

### ISSUE THREAD

**Issue by Pavestone6556** [WaLLy3K/Pi-hole-Block-Page#17]
I have a pihole install on CentOS docker that works well. How would I go about installing  your block page to a container like that? 

This is the docker I use:
https://hub.docker.com/r/diginc/pi-hole/

Really liked your hosted ad listed and thought this project would be nice to try.

**Comment by WaLLy3K** [comment]
Having not used docker, I don't know what, if anything is different. Sorry I can't be of more help!
