### ISSUE TITLE
landingpage.php

### ISSUE THREAD

**Issue by technicalpyro** [WaLLy3K/Pi-hole-Block-Page#20]
i haven't set any custom landing page but this is what shows for blocked domains 

![2017-05-23_17-19-00](https://cloud.githubusercontent.com/assets/24907599/26380497/21cb249e-3fdc-11e7-94a0-8ae227aab283.jpg)

**Comment by WaLLy3K** [comment]
Hey @technicalpyro, the block page currently doesn't work under Pi-hole's development branch. Sorry, there's no good solution I have to fix that right now!

**Comment by technicalpyro** [comment]
no worries thought i had managed to mess something up not a major functional issue more of a hey this seems off kinda one 

Thanks
