### ISSUE TITLE
Airelle-hrsk blocks "Amazon.com"

### ISSUE THREAD

**Issue by IAreKyleW00t** [WaLLy3K/Pi-hole-Block-Page#21]
This file is marked to have no notable false-positives, but blocks `Amazon.com` (line 15165). This can obviously be whitelisted, but should at least be marked otherwise.

**Edit**: Sorry, this is in the wrong repo.

**Comment by WaLLy3K** [comment]
Hey @IAreKyleW00t, and apologies for the time it took to reply to this. You're right in that [my other repo](https://github.com/WaLLy3K/wally3k.github.io) would be the best one to submit issues on, but none the less, this site does seem to be a false positive.

I've sent an email off to the list maintainer, asking for their input. I'll happily update this ticket once I get a reply.

Thanks for the report! :smile:

**Comment by WaLLy3K** [comment]
Airelle's just informed me that the entry should be removed in the next update.

**Comment by IAreKyleW00t** [comment]
That's great! Thank you for taking care of that. In the future, should I report false-positive domains to your other repo or try to contact the list maintainer directly? I didn't see any contact info for the lists.

**Comment by WaLLy3K** [comment]
As I'm just forwarding a message to the respective list maintainer, it'd be better to contact them directly. If they don't follow up in a timely manner (or shoot down your requests for valid whitelist removals), then opening a ticket on my [other repo](https://github.com/WaLLy3K/wally3k.github.io/issues) (or contacting me via other methods) means I can at least *not* recommend them as a list if I don't already have them marked with a cross.

You should be able to find a list maintainer email by toggling the source, heading to their website and then snoop around for their contact details (or email the admin listed on the whois lookup).

**Comment by IAreKyleW00t** [comment]
I completely missed the "Toggle list sources" button - my bad! Thanks for the help and info. :)
