### ISSUE TITLE
whitelisting without password

### ISSUE THREAD

**Issue by xxcriticxx** [WaLLy3K/Pi-hole-Block-Page#25]
No password set - whitelisting with password not supported

@WaLLy3K is there any way to go around this?

**Comment by WaLLy3K** [comment]
Unfortunately no, not at this time. The whitelisting functionality of my side project is a direct copy of what's in the Pi-hole block page, and I don't know enough Javascript in order to add the functionality in myself.

It is something we're looking into though! :smile:
