### ISSUE TITLE
No phbp.ini created in /var after Installation

### ISSUE THREAD

**Issue by pchristod** [WaLLy3K/Pi-hole-Block-Page#3]
Hi,
might be a silly thing on my part, everything is working, but I can't find the Config File, i seem to only have the .BAK phbp file, but everything is working. Is there any place else this file is stored?
Thanks

**Comment by WaLLy3K** [comment]
Thanks so much for reporting this, I don't know how I didn't spot it!

You can fix my screwup by issuing the following command: `sudo mv /var/phbp.ini.BAK /var/phbp.ini`
