### ISSUE TITLE
What is the "phbp.php" section for? 

### ISSUE THREAD

**Issue by r0ckarong** [WaLLy3K/Pi-hole-Block-Page#4]
I ran the script line by line and as far as I can tell it installed alright. 
I can't figure out what this line is supposed to do:

`[ -f "/var/phbp.php" ] && sudo mv /var/phbp.php /var/phbp.old.BAK`

At no point is a phbp.php created and I can't find a file with that name on my raspi anywhere. Is this a remnant of an older version of the install steps?

**Comment by WaLLy3K** [comment]
That's a good question! [phbp.php](https://github.com/WaLLy3K/Pi-hole-Block-Page/blob/1aa34dd6f9e0cf6a5f4082752cf489e917c1c0f9/phbp.php) was the old config file, prior to moving to the more secure and appropriate INI format.

A backup is made in case the user may have made edits to it, so the settings can be put into `phbp.ini`.

Hopefully that answers your question - but if not, you're more than welcome to let me know! :smile:
