### ISSUE TITLE
[ERROR]: The configured landpage 'landing.php' does not exist.

### ISSUE THREAD

**Issue by syko86** [WaLLy3K/Pi-hole-Block-Page#6]
hello Wally3k

Thanks for your good work! 

i have a problem with the landingpage, it doesnt show up, i think i do something wrong but i dont know what, im new to ubuntu server.

ive put the landing.php in this directory  /var/www/html/landing.php
and in the phbp.ini its pointing to that file, ive watching tutorials and stuf but im stuck now for 2 days

can or would you point me into the good direction?

**Comment by WaLLy3K** [comment]
Thanks for the praise, but sorry to hear you're having an issue! Could you provide the output of `http://doubleclick.net/?debug=conf` please?

**Comment by syko86** [comment]
Hey
Thanks for your quik response

I get a message  this site is unavaileble
The dns from double click.Net cant be found

Err name not resolved



Met vriendelijke groet,

Sander 


-------- Oorspronkelijk bericht --------
Van: WaLLy3K <notifications@github.com>
Datum: 09-02-17 03:12 (GMT+01:00)
Aan: WaLLy3K/Pi-hole-Block-Page <Pi-hole-Block-Page@noreply.github.com>
Cc: syko86 <shawantia@hotmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [WaLLy3K/Pi-hole-Block-Page] [ERROR]: The configured landpage 'landing.php' does not exist. (#6)


Thanks for the praise, but sorry to hear you're having an issue! Could you provide the output of http://doubleclick.net/?debug=conf please?

**Comment by WaLLy3K** [comment]
Thanks for the reply! What you're seeing may hint that there is an issue with your Pi-hole installation.

Could you please provide the results of `pihole status` from Terminal/SSH?

**Comment by syko86** [comment]
Dns service is running
Pi-hole blocking is enabled

That looks good to me ?

and debug info: 
`::: Beginning Pi-hole debug at Thu Feb  9 09:53:50 CET 2017!
:::
::: This process collects information from your Pi-hole, and optionally uploads
::: it to a unique and random directory on tricorder.pi-hole.net.
:::
::: NOTE: All log files auto-delete after 24 hours and ONLY the Pi-hole develope                                                                                        rs
::: can access your data via the given token. We have taken these extra steps to
::: secure your data and will work to further reduce any personal information ga                                                                                        thered.
:::
::: Please read and note any issues, and follow any directions advised during th                                                                                        is process.
:::
:::  Detecting Installed Package Versions:
:::       Pi-hole: v2.12.1
:::       WebUI: v2.4
:::       lighttpd/1.4.35
:::       PHP 7.0.13-0ubuntu0.16.04.1 (cli) ( NTS )
:::       Pi-hole branch:  master
:::       Pi-hole rev:     v2.12.1-0-g5333895
:::       AdminLTE branch: master
:::       AdminLTE rev:    v2.4-0-g406877d
:::
:::  Detecting existence of /etc/pihole/setupVars.conf:
:::       File exists and was successfully sourced
:::
:::  Detecting installed OS Distribution
:::
:::  Checking processor variety
:::
:::  IP Address Information
:::       IPv6 addresses located
:::       IPv4 addresses located
:::        Pinging default IPv4 gateway: Gateway responded.
:::        Pinging Internet via IPv4: Query responded.
:::
:::  Daemon Process Information
:::     Checking http port for lighttpd listener.
:::       Correctly configured.
:::       Correctly configured.
:::
:::  Daemon Process Information
:::     Checking domain port for dnsmasq listener.
:::       Correctly configured.
:::       Correctly configured.
:::
:::  Processes Check
:::     Logging status of lighttpd and dnsmasq...
:::
:::  Resolver Functions Check
:::     Checking for necessary lighttpd files.
:::
:::  Detecting existence of /etc/lighttpd/lighttpd.conf:
:::       File exists
:::
:::  Detecting existence of /var/log/lighttpd/error.log:
:::       File exists
:::
:::
:::  Detecting existence of /etc/dnsmasq.conf:
:::       File exists
:::
:::  Detecting existence of /etc/dnsmasq.d/01-pihole.conf:
:::       File exists
:::
:::  Detecting existence of /etc/pihole/whitelist.txt:
:::       File exists
:::
:::  Detecting existence of /etc/pihole/blacklist.txt:
:::       File exists
:::
:::  Detecting existence of /etc/pihole/adlists.list:
:::       File exists
:::
:::  Analyzing gravity.list
:::
:::  Analyzing pihole.log
:::
::: --= User Action Required =--
::: Try loading a site that you are having trouble with now from a client web br                                                                                        owser..
:::     (Press CTRL+C to finish logging.)
:::
:::  pihole.log
::: Logging will automatically teminate in 60 seconds
::: Finshed debugging!.
::: The debug log can be uploaded to tricorder.pi-hole.net for sharing with developers only.
::: Would you like to upload the log? [y/N] n
::: Log will NOT be uploaded to tricorder.
::: There was an error uploading your debug log.
::: Please try again or contact the Pi-hole team for assistance.
::: A local copy of the Debug log can be found at : /var/log/pihole_debug.log
`

**Comment by WaLLy3K** [comment]
That does look good! Is the contents of [the block page](https://github.com/WaLLy3K/Pi-hole-Block-Page/blob/master/index.php) located at `/var/www/html/index.php` on your server?

Also, what is the content that you have placed within `landing.php`?

**Comment by syko86** [comment]
contents of the block page located at /var/www/html/index.php on your server:    yes

Also, what is the content that you have placed within landing.php?

when i open this on /var/www/html/landing.php   it ask if it must be a new file ? See 
![landing](https://cloud.githubusercontent.com/assets/25650840/22776587/821faf04-eeb0-11e6-8583-9b88364e37d9.gif)
screenshot

**Comment by syko86** [comment]
What must be in there? Sorry for not understanding !

**Comment by WaLLy3K** [comment]
So, we know that Pi-hole is working as expected, which is good - but I can't confirm that the block page is working as expected yet (and if that doesn't work, the redirect to the landing page won't work either).

Since you're not seeing the block page when browsing to [http://doubleclick.net](http://doubleclick.net), could you try something like [http://lb.usemaxserver.de](http://lb.usemaxserver.de)? (It's the first line of Steven Black's host file, which is a default block list for Pi-hole), but any page that results in the block page is all we need.

Also, for what it's worth, `landing.php` can simply contain "Hello World", or anything else that you want - it's where your block page will redirect you if you are hosting content on your Pi-hole server, that isn't blocked (Such as your Pi's IP address or domain name).

**Comment by syko86** [comment]
i think its good now ??

it doenst look so fancy as your exemple ?



![result](https://cloud.githubusercontent.com/assets/25650840/22777808/bb350358-eeb4-11e6-8c2b-2093a1fece57.gif)

**Comment by WaLLy3K** [comment]
The page is definitely correct, but it looks like it's retrieving the CSS from `/var/www/html/pihole/blockingpage.css`, which it shouldn't be (that's for the default block page that's shipped with Pi-hole).

Could you provide the output of `http://lb.usemaxserver.de?debug=conf` please? I'm interested to see if you are manually specifying `customCss` from within `/var/phbp.ini`.

**Comment by syko86** [comment]
output of http://lb.usemaxserver.de?debug=conf :
`Server/OS: Ubuntu
› OS Uptime: 00:21:53
› Task Load: 0.27, 0.14, 0.05 (1/68 active)
› CPU usage: 5% (Temp: N/A, Cores: 1)
› RAM usage: 11% (211 MB of 2 GB used)
› PHP usage: 2 MB (128M limit)
› P-H usage: 158,597 domains (15/178 blocked)
› PHBP info: v2.2.0 (RCI: v2.2.0, 0a6e236c)
› PHBP conf: Passwd: 1, WL: 1, Updates: 1
› Adlists.list: 10 blocklists
› Queryads.php: 3 results (0,6,7)
› Lb.usemaxserver.de: 3 lists (Advertising)
› Generated in: 0.16s

User Config Array
(
    [classFile] => https://raw.githubusercontent.com/WaLLy3K/wally3k.github.io/master/classification.ini
    [classUpdateTime] => 172800
    [landPage] => landing.php
    [blankGif] => true
    [blockImage] => https://wally3k.github.io/style/blocked.svg
    [customIcon] => http://pi.hole/admin/img/favicon.png
    [customCss] => http://pi.hole/pihole/blockingpage.css
    [customLogo] => https://wally3k.github.io/style/phv.svg
    [adminEmail] => user@redacted.com
    [checkUpdates] => true
    [selfDomain] => redacted.com
)

`looks you are right  with blockingpage.css.
but i dont know how to change it

**Comment by WaLLy3K** [comment]
The following should sort the style issue out for you: ` sudo sed -i 's/customCss/;customCss/' /var/phbp.ini` (but any text editor, such as `nano`, can do the job). After that, you can confirm that the block page looks like [the example screenshots](https://github.com/WaLLy3K/Pi-hole-Block-Page#what-does-this-do).

If you'd like to still have a landing page (That is, content that shows when you browse to your Pi-holes IP address), add some content into `/var/www/html/landing.php` and see if it shows up when browsing to that IP address (or hostname).

Hopefully, this all works as expected - but if not, please let me know!

**Comment by syko86** [comment]
Sir you are the best ! its all working fine now !

thanks for your help and i hope i wasnt too dumb :)

thank you so much !   

are you on the dev team of pi-hole ?

![fancy block](https://cloud.githubusercontent.com/assets/25650840/22778948/2786aaa8-eeb9-11e6-9622-f75234239315.gif)
![pi-hole-ip](https://cloud.githubusercontent.com/assets/25650840/22778956/2ce337e6-eeb9-11e6-99a1-ac20ec59bedb.gif)

**Comment by WaLLy3K** [comment]
I don't feel you were dumb at all. It's provided me with very useful 'cross-language barrier' feedback (if that makes sense?), so thank you for opening a ticket on the issue, and for being as responsive as you have been!

I'm not on the Pi-hole dev team, though I do keep in touch with them when necessary - usually on the [Pi-hole subreddit](https://www.reddit.com/r/pihole).

Since everything appears to be working as expected, I'll close this issue - but if you do have any questions or concerns, you are more than welcome to let me know!
