### ISSUE TITLE
Custom port admin page on synology NAS

### ISSUE THREAD

**Issue by iroQuai** [WaLLy3K/Pi-hole-Block-Page#7]
I install pi-hole on my synology NAS. A custom port is needed for the admin page. When I installed your custom block page, the admin page wasn't available anymore. Not knowing what to do, i've repaired pi-hole (through the 'pihole -r' command). I needed to manual edit the custom port to access the admin page again. 

On the admin page there is nothing different going on. On the IP:port of the NAS (192.168.2.11:5005, without /admin/ added) a custom block page is visible, mentioning that a land page isn't configured.

Can you please help me, tell me how to proceed? Thanks in advance!

**Comment by WaLLy3K** [comment]
Sorry to hear you're having issues with the block page, iroQuai!

To confirm your question: when you install the custom Block Page, you're unable to access Pi-hole web admin - is that correct?

If so, a setup like yours isn't something I've ever taken into account - so I need to get a better understanding of how your NAS is working:

* Does your hardware run two HTTP daemons? That is, both [192.168.2.11](http://192.168.2.11) and [192.168.2.11:5005](http://192.168.2.11:5005) open different webpages?
* Does going to [192.168.2.11:5005/admin](http://192.168.2.11:5005/admin) bring up the Pi-hole Admin?
* When browsing to the visible block page, does it show the correct stylesheet?
* What is the output of `ls -l /var/www/html`?

If I've misunderstood anything, please let me know :)

**Comment by iroQuai** [comment]
You can read more about my setup here:  https://discourse.pi-hole.net/t/how-do-i-install-pi-hole-on-a-synology-nas/289

To answer your questions:
- Different  ports open different webpages on the nas. 192.168.2.11 forwards to the nas admin panel on :5000, :5005 opens pi-hole, :9091 opens transmission, :8085 opens sick beard, and so on... (all those ports are changable if needed, but from what i understand it's not desired to change :80 to the pihole admin panel)
- :5005/admin usualy brings up the Pi-Hole admin, indeed (but not after installing your custom block page)
- when i go to :5005 (without /admin), I see a page that is styled like your custom block page, telling me that the landing page isn't configured. 
- I'll check the output of  `ls -l /var/www/html` soon as i get home!

Already thanks for your quick reply!

**Comment by iroQuai** [comment]
Output of `ls -l /var/www/html`

```
total 52
drwxr-xr-x 7 root     root      4096 Feb 5 21:52 admin
-rw-r--r-- 1 www-data www-data  5328 Feb 6 20:27 classification.ini
-rw-r--r-- 1 root     root      3373 Dec 9 00:37 index.lighttpd.orig
-rwxr-xr-x 1 root     root     28720 Feb 6 20:10 index.php
drwxr-xr-x 2 root     root      4096 Jan 3 20:42 pihole
```

**Comment by WaLLy3K** [comment]
Thanks for the extra information, that helps a lot!

Honestly, it's not immediately obvious to me why installing `/var/www/html/index.php` would render [192.168.2.11/admin](http://192.168.2.11/admin) inaccessible (I'm sure the answer will smack me in the face though, as this kind of thing always does!). Is it the same if you use [pi.hole/admin](http://pi.hole/admin), by any chance?

Also, could you provide a screenshot (or some reference) of what exactly happens when you browse to [192.168.2.11/admin](http://192.168.2.11/admin)?

Cheers!

**Comment by iroQuai** [comment]
is it correct you forgot the port number in all urls? Because i always need to add :5005 when i want to visit my admin console. 

The only plausible reason 192.168.2.11:5005/admin/ isn't available after i install your block page, would be because /etc/lighttpd/lighttpd.conf gets overwritten. Because thats where i change the port number... 
  
A screenshot of 192.168.2.11:5005/admin after installing your block page isn't all that interesting. It would be the same as visiting this site: http://www.thisisnotavalidwebsite.com/ 

btw, I've updated to the latest version (v2.13 / Web v2.5). One of the changes is that http://pi.hole redirects to pi.hole/admin/, so I cannot show you anymore what was shown there (it talked about not having configured a langing page, with your formatting etc)

edit: sorry wrong button, closed it by accident!

**Comment by iroQuai** [comment]
your script does do something btw...
I got a few popups showing the standard page

**Comment by WaLLy3K** [comment]
Do you know what HTTP daemon runs on port 80, and which runs on port 5005? If they're both using Lighttpd, I think I *might* understand why this issue is happening.

The *only* config change made is `url.rewrite-once = ( "pihole/index.php" => "/index.php" )` within `/etc/lighttpd/conf-enabled/phbp.conf`. This in itself shouldn't be interfering with accessing `192.168.2.11:5005/admin`, but if they're both running Lighttpd and reading the same config, I suspect it may cause some issues.

You can confirm this for me by renaming `index.php` and testing whether the issue persists.

Thanks!

**Comment by iroQuai** [comment]
thanks for all your help, but i decided to stop using pihole on my nas. Even though it sounds awesome, it's just too much of a hassle tweaking all those small things. the various replys in the discourse FAQ topic support this...

I had a pi zero lying around, so i've plugged that one in and i'm busy installing and configuring everything.

**Comment by WaLLy3K** [comment]
I'm sorry I couldn't make the troubleshooting process at least a little smoother for you! I hate having to constantly go back and forth on the same topic, especially when it's about something I can't fully grasp.

Thanks for your patience up till now, and I hope everything goes smoothly from here on out! If you run into any further issues with PHBP, please don't hesitate to contact me. :)
